"""add col patronomic

Revision ID: 5cd6589d94c5
Revises: a32371b1c0fd
Create Date: 2025-02-12 00:55:41.555344

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5cd6589d94c5"
down_revision: Union[str, None] = "5aeafe8780b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("patronomic", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "patronomic")
    # ### end Alembic commands ###
