"""add col surname

Revision ID: a32371b1c0fd
Revises: 5aeafe8780b4
Create Date: 2025-02-12 00:53:34.949218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a32371b1c0fd'
down_revision: Union[str, None] = '5aeafe8780b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('has_sale', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_sale')
    op.drop_column('users', 'surname')
    # ### end Alembic commands ###
